03_django/02_TEMPLATE_VIEW/data/urls.py
from django.urls import path
from .import views

app_name = 'data'

urlpatterns = [
    # full url -> data/
    path('', views.index, name='index'),

    # data/hello/<name>/ -> Variable Routing
    path('hello/<name>/', views.hello, name='hello'),
    # hello/neo/ -> 안녕 neo
    # hello/andy -> 안녕 andy


    # full url -> data/input/
    path('user_input/', views.user_input, name='user_input'),
    
    # data/user_output
    path('user_output/', views.user_output, name='user_output'),

]

03_django/02_TEMPLATE_VIEW/review/urls.py
from django.urls import path
from . import views

# 변수명은 반드시 app_name이어야 함
app_name = 'review'

# URL 구성 맨 앞에 'review/'는 이미 master url에서 검사가 끝났음.
urlpatterns = [
    # 패턴 '(review/)index/'가 요청으로 들어온다면, index함수실행!!
    path('index/', views.index, name='index'),
    # review/hello/
    path('hello/', views.hello, name='hello'),
]

03_django/02_TEMPLATE_VIEW/template_view/urls.py
# Master URL
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # URL pattern이 'reviews/'로 시작하면 -> 'review/urls.py에게 넘기겠다.
    path('review/', include('review.urls')),
    # url pattern이 'data'/로 시작하면 -> 'data/urls.py에게 넘기겠다.
    path('data/', include('data.urls')),
]

03_django/02_TEMPLATE_VIEW/data/models.py
from django.db import models

# Create your models here.

03_django/02_TEMPLATE_VIEW/review/models.py
from django.db import models

# Create your models here.

03_django/02_TEMPLATE_VIEW/data/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'data/index.html')

def hello(request, name):
    context = {
        'name' : name
    }
    return render(request, 'data/hello.html',context)

def user_input(request):
    return render(request, 'data/user_input.html')

def user_output(request):
    c = int(request.POST['cel'])
    f = c * 1.8 + 32
    context = {
        'f' : f,
        'username' : request.POST['username'],
        'password' : request.POST['password'],

    }
    return render(request, 'data/user_output.html', context)

03_django/02_TEMPLATE_VIEW/review/views.py
from django.shortcuts import render


def index(request):
    
    # Res -> HTML Render
    # render(1. reqeust | 2. html 이름 | 3. 넘길 데이터)
    return render(request, 'review/index.html')

def hello(request):
    return render(request, 'review/hello.html')

03_django/02_TEMPLATE_VIEW/review/templates/review/hello.html
{% include 'base.html'%}

{% block content %}
    <h1>Review/hello</h1>

    <a href="{% url 'review:index' %}">Index</a>
{% endblock content %}

03_django/02_TEMPLATE_VIEW/review/templates/review/index.html
{% include 'base.html' %}

{% block content %}
    <h1>Review/index</h1>

    <a href="{% url 'review:hello' %}">Hello</a>

{% endblock content %}  

03_django/02_TEMPLATE_VIEW/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% block content %}{% endblock content %}
</body>
</html>