03_django/MTV/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # blog/create/
    path('create/', views.create, name='create'),

    # blog/
    path('', views.index, name='index'),
    # blog/1/
    path('<int:article_pk>/', views.detail, name='detail'),
    
    # blog/1/edit/
    path('<int:article_pk>/edit/', views.edit, name='edit'),
    # blog/1/update/
    path('<int:article_pk>/update/', views.update, name='update'),

    # blog/1/delete/
    path('<int:article_pk>/delete/', views.delete, name='delete'),
]

'''
URL
1. Resource 를 표현
2. 명사형
3. 확실히 구분
4. (동사는 빼라)
'''

03_django/MTV/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # board
    path('', views.index, name='index'),

    # board/new/
    path('new/', views.new, name='new'),

    # board/create/
    path('create/', views.create, name='create'),

    # board/1/
    path('<int:posting_pk>/', views.detail, name='detail'),

    # board/1/edit(수정)
    path('<int:posting_pk>/edit/', views.edit, name='edit'),

    # board/1/update -> db에 저장하는것
    path('<int:posting_pk>/update/', views.update, name='update'),

    # board/1/delete/
    path('<int:posting_pk>/delete/', views.delete, name='delete'),
]

03_django/MTV/mtv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('board/', include('board.urls')),
]

03_django/MTV/blog/models.py
from django.db import models

# 1개의 클래스는 1개의 테이블(표)와 매칭됨
class Article(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()

    # 생성시 자동으로 채워지도록 -> DateTimeField만 가능
    created_at = models.DateTimeField(auto_now_add=True)

    # 생성/수정시 자동으로 채워지도록 -> DateTimeField만 가능
    updated_at = models.DateTimeField(auto_now=True)

03_django/MTV/board/models.py
from django.db import models


class Posting(models.Model):
    subject = models.CharField(max_length=100)
    description = models.TextField()    

03_django/MTV/blog/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    # 1. 유효성검사 (validation)
    # 2. html 안에 <input> 태그 만들기 싫다
    # 3. 저장할때 request.POST에서 하나하나 꺼내기 귀찮

    title = forms.CharField(min_length=2, max_length=100)
    

    class Meta:
        model = Article
        fields = ('title', 'content',)

03_django/MTV/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Article
from .forms import ArticleForm

# 글 목록 화면 (Read)
def index(request):
    # 글 목록 조회
    # db > article > 모든 레코드 조회
    articles = Article.objects.all()  # QuerySet(List)
    context = { 'articles': articles, }
    return render(request, 'blog/index.html', context)


# 글 상세 화면 (Read)
def detail(request, article_pk):
    # db > articles > 특정 레코드 조회    
    article = get_object_or_404(Article, pk=article_pk)
    context = { 'article': article, }
    return render(request, 'blog/detail.html', context)


# 글 쓰기 화면 or 저장 or 반려
def create(request):
    # 만약 POST 방식으로 요청이 왔다면
    if request.method == 'POST':
        # 박스에 넣고
        article_form = ArticleForm(request.POST)
        # 검사하고
        if article_form.is_valid():
            # 괜춘하니 save => redirect
            article = article_form.save()
            return redirect('blog:detail', article.pk)
    
    # 만약 GET 방식으로 요청이 왔다면       
    elif request.method == 'GET':
        # 빈 박스를
        article_form = ArticleForm()

    # 1. POST 방식인데 안괜찮으면, 반려당한 article_form
    # 2. GET 방식이면 빈 article_form
    context = {'article_form': article_form, }
    return render(request, 'blog/form_new.html', context)



# 글 수정 화면
def edit(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    context = { 'article': article, }
    return render(request, 'blog/edit.html', context)

# 글 DB에 실제 수정
def update(request, article_pk):
    # 기존의 article 객체 조회(레코드 검색)
    article = get_object_or_404(Article, pk=article_pk)
    article.title = request.POST['title']
    article.content = request.POST['content']
    article.save()
    # 저장하고 detail 로 redirect 하자!
    return redirect('blog:detail', article.pk)



# 글 삭제 ?? (Delete)
def delete(request, article_pk):
    if request.method == 'POST':
        # 1. 고른다.
        article = get_object_or_404(Article, pk=article_pk)
        # 2. 지운다.
        article.delete()
    return redirect('blog:index')

03_django/MTV/board/views.py
from django.shortcuts import render, redirect
from .models import Posting

def index(request):
    # 테이블에서 목록 조회
    # db posing에서 레코드 전체 조회
    # 기본 id- > 오름차순
    # postings = Posting.objects.all()

    # id 내림차순 (python)
    # postings = Posting.objects.all()[::-1]

    # id 내림차순 (DB)
    postings = Posting.objects.order_by('-pk')

    context = {
        'postings':postings,
    }
    return render(request, 'board/index.html', context)

# 글 상세 화면(Read)
def detail(request, posting_pk):
    posting = Posting.objects.get(pk=posting_pk)
    context={
        'posting':posting,
    }
    return render(request, 'board/detail.html', context)


# 글 쓰기 화면(new)
def new(request):
    return render(request, 'board/new.html')

# 작성한 데이터 실제 db 저장
def create(request):
    posting = Posting()
    posting.subject = request.POST['subject']
    posting.description = request.POST['description']
    posting.save()

    return redirect('board:detail', posting.pk)

# 수정 화면
def edit(request, posting_pk):
    posting = Posting.objects.get(pk=posting_pk)
    context={
        'posting':posting,
    }
    return render(request, 'board/edit.html', context)
    
# db에 실제 수정
def update(request, posting_pk):
    posting = Posting.objects.get(pk=posting_pk)
    posting.subject = request.POST['subject']
    posting.description = request.POST['description']
    posting.save()

    return redirect('board:detail', posting.pk)


# 삭제
def delete(request, posting_pk):
    if request.method == 'POST':
        posting = Posting.objects.get(pk=posting_pk)
        posting.delete()

    return redirect('board:index')

03_django/MTV/blog/templates/blog/detail.html
{% include 'base.html' %}

{% block content %}
<h1>{{article.title}}</h1>
<span>
    {{article.created_at}}
    {{article.updated_at}}
</span>

<p>
    {{article.content}}
</p>

{% comment %} 알파벳순 a -> b (버튼) {% endcomment %}
<div>
    
    <a href="{% url 'blog:edit' article.pk %}">
        <button>수정</button>
    </a>

     <form action="{% url 'blog:delete' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" value='삭제'>
     </form>
</div>
{% endblock content %}

03_django/MTV/blog/templates/blog/edit.html
{% include 'base.html' %}

{% block content %}
<h1>Edit Article</h1>

<form action="{% url 'blog:update' article.pk %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="title">제목</label>
        <input id="title" name="title" type="text" value={{article.title}}>
    </div>

    <div>
        <label for="content">내용</label>
        <textarea name="content" id="content" cols="30" rows="10">{{article.content}}</textarea>
    </div>

    <div>
        <input type="submit" value="얍">
    </div>
</form>

{% endblock content %}

03_django/MTV/blog/templates/blog/form_new.html
{% include 'base.html' %}

{% block content %}

<h1>New Article</h1>

<p>ModelForm 을 통해서 만들어짐</p>

<form action="{% url 'blog:create' %}" method="POST">
    {% csrf_token %}
    
    {{ article_form.as_p }}

    <button>제출</button>
</form>

{% endblock content %}

03_django/MTV/blog/templates/blog/index.html
{% include 'base.html' %}

{% block content %}
<h1>Index Page</h1>

{% comment %} 모든 게시글의 제목만 리스트로 확인 {% endcomment %}
<ul>
    {% for article in articles %} 
        <li>
            <a href="{% url 'blog:detail' article.pk %}">
                {{article.title}}
            </a>
        </li>
    {% endfor %}
</ul>



{% endblock content %}

03_django/MTV/blog/templates/blog/new.html
{% include 'base.html' %}

{% block content %}

<h1>New Article</h1>

<form action="{% url 'blog:create' %}" method="POST">
    {% csrf_token %}
    <div>
        <label for="title">제목: </label>
        <input id="title" name="title" type="text">
    </div>

    <div>
        <label for="content">내용: </label>
        <textarea name="content" id="content" cols="30" rows="10"></textarea>
    </div>

    <div>
        <input type="submit" value="얍">
    </div>
</form>
{% endblock content %}

03_django/MTV/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <ul>
            <li>
                <a href="{% url 'blog:index' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'blog:new' %}">New</a>
            </li>
        </ul>
    </nav>
    {% block content %}{% endblock content %}
</body>
</html>

03_django/MTV/templates/base_board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <nav>
        <ul>
            <li>
                <a href="{% url 'board:index' %}">Home</a>
            </li>
            <li>
                <a href="{% url 'board:new' %}">New</a>
            </li>
        </ul>
    </nav>
    {% block content %}{% endblock content %}
</body>
</html>