03_django/RECAP/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    # accounts/signup
    path('signup/', views.signup, name='signup'),

    # accounts/login/
    path('login/', views.login, name='login'),

    # accounts/logout/
    path('logout/', views.logout, name='logout'),
]

03_django/RECAP/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    # polls/create/
    path('create/', views.create_question, name='create_question'),
    # polls/
    path('', views.question_index, name='question_index'),
    # polls/1
    path('<int:question_pk>/', views.question_detail, name='question_detail'),
    # polls/1/update
    path('<int:question_pk>/update/', views.update_question, name='update_question'),
    # polls/1/delete
    path('<int:question_pk>/delete/', views.delete_question, name='delete_question'),

    # polls/1/replies/create/
    path('<int:question_pk>/replies/create/', views.create_reply, name='create_reply'),

    # polls/1/replies/2(reply_id_)/upvote/
    path('<int:question_pk>/replies/<int:reply_pk>/upvote/', views.reply_upvote, name='reply_upvote'),

    # polls/1/repilies/2/delete
    path('<int:question_pk>/replies/<int:reply_pk>/delete/', views.delete_reply, name='delete_reply'),
]

03_django/RECAP/recap/urls.py
# Master urls.py
from django.contrib import admin
from django.urls import path, include

def to_main(request):
    from django.shortcuts import redirect
    return redirect('polls:question_index')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('polls/', include('polls.urls')),
    path('', to_main),
]

03_django/RECAP/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>Logged in as [{{request.user}}]</p>
    <ul>
        <li>
            <a href="{% url 'polls:question_index' %}">Home</a>
        </li>
        {% comment %} 사용자가 login 안했다면 {% endcomment %}
        {% if not request.user.is_authenticated %}
        <li>
            <a href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li>
            <a href="{% url 'accounts:signup' %}">Signup</a>
        </li>
        {% comment %} 사용자가 login 했다면 {% endcomment %}
        {% else %}
        <li>
            <a href="{% url 'polls:create_question' %}">New Question</a>
        </li>
        <li>
            <a href="{% url 'accounts:logout' %}">Logout</a>
        </li>
        {% endif %}
    </ul>
    {% block content %}{% endblock content %}
</body>
</html>