03_django/RECAP/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    # polls/create/
    path('create/', views.create_question, name='create_question'),
    # polls/
    path('', views.question_index, name='question_index'),
    # polls/1
    path('<int:question_pk>/', views.question_detail, name='question_detail'),
    # polls/1/update
    path('<int:question_pk>/update/', views.update_question, name='update_question'),
    # polls/1/delete
    path('<int:question_pk>/delete/', views.delete_question, name='delete_question'),

    # polls/1/replies/create/
    path('<int:question_pk>/replies/create/', views.create_reply, name='create_reply'),

    # polls/1/replies/2(reply_id_)/upvote/
    path('<int:question_pk>/replies/<int:reply_pk>/upvote/', views.reply_upvote, name='reply_upvote'),

    # polls/1/repilies/2/delete
    path('<int:question_pk>/replies/<int:reply_pk>/delete/', views.delete_reply, name='delete_reply'),
]

03_django/RECAP/recap/urls.py
# Master urls.py
from django.contrib import admin
from django.urls import path, include

def to_main(request):
    from django.shortcuts import redirect
    return redirect('polls:question_index')


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('polls/', include('polls.urls')),
    path('', to_main),
]

03_django/RECAP/polls/models.py
# polls/models.py
from django.db import models
from django.conf import settings

class Question(models.Model):
    title = models.CharField(max_length=200)
    # 알아서 db 컬럼은 user_id
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE
    )

class Reply(models.Model):
    content = models.CharField(max_length=200)
    vote = models.IntegerField(default=0)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, 
        on_delete=models.CASCADE
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE
    )

03_django/RECAP/polls/forms.py
from django import forms
from .models import Question, Reply

class QuestionForm(forms.ModelForm):
    title = forms.CharField(min_length=3, max_length=200)
    class Meta:
        model = Question
        # 모든 필드(title,user)들 중에 아래 필드만 HTML에 보여주고 + 검증함
        fields = ('title', )

class ReplyForm(forms.ModelForm):
    content = forms.CharField(min_length=3, max_length=200)
    class Meta:
        model = Reply
        fields = ('content',)

03_django/RECAP/polls/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.http import HttpResponseForbidden
from django.views.decorators.http import require_http_methods, require_safe, require_POST
from django.contrib.auth.decorators import login_required
from .models import Question, Reply
from .forms import QuestionForm, ReplyForm

@login_required
@require_http_methods(['GET','POST'])
def create_question(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            # 이 question 객체의 user 항목은(작성자는) 요청을 보낸 사용자이다.
            question.user = request.user
            question.save()
            return redirect('polls:question_detail', question.pk)
    else :
        form = QuestionForm()
    context = {'form':form,}
    return render(request, 'polls/question_form.html', context)

@require_safe
def question_index(request):
    questions = Question.objects.all()
    context = {'questions' : questions}
    return render(request, 'polls/question_index.html', context)

@require_safe
def question_detail(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    form = ReplyForm()
    context = {
        'question':question,
        'form' : form,
        }
    return render(request, 'polls/question_detail.html', context)

@login_required
@require_http_methods(['GET', 'POST'])
def update_question(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)

    # 요청 보낸 사용자가 질문 작성자가 아니라면,
    if request.user != question.user:
        return HttpResponseForbidden('권한이 없습니다.')

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save()
            return redirect('polls:question_detail', question.pk)

    else:
        form = QuestionForm(instance=question)
    context = {'form' : form}
    return render(request, 'polls/question_form.html', context)

@login_required    
@require_POST
def delete_question(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)

    # 요청 보낸 사용자가 질문 작성자가 아니라면,
    if request.user != question.user:
        return HttpResponseForbidden('권한이 없습니다.')

    question.delete()
    return redirect('polls:question_index')

@login_required
@require_POST
def create_reply(request, question_pk): # 댓글 저장만 담당
    question = get_object_or_404(Question, pk=question_pk)
    form = ReplyForm(request.POST)
    if form.is_valid():
        reply = form.save(commit=False)
        reply.question = question
        reply.user = request.user
        reply.save()
    return redirect('polls:question_detail', question_pk)

@login_required
@require_POST
def reply_upvote(request, question_pk, reply_pk): # polls/1(question_pk)/replies/2(reply_pk)/upvote/
    question = get_object_or_404(Question, pk=question_pk)
    # 1. reply 하나를 잡고
    reply = get_object_or_404(Reply, pk=reply_pk)
    # 누른 사람(요청 보낸 사람)이 reply 작성자가 아닐 때만
    if request.user != reply.user:
        reply.vote += 1
        reply.save()
    return redirect('polls:question_detail', question.pk)


@login_required
@require_POST
def delete_reply(request, question_pk, reply_pk):
    question = get_object_or_404(Question, pk=question_pk)
    reply = get_object_or_404(Reply, pk=reply_pk)
    # 댓글 작성자와 삭제버튼 누른 사람이 같을 때만 삭제
    if request.user != reply.user:
        return HttpResponseForbidden('권한이 없습니다.')
    reply.delete()
    return redirect('polls:question_detail', question.pk)

03_django/RECAP/polls/templates/polls/question_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{question.title}}</h1>
<p>by - {{question.user.username}} ({{question.user.mbti}})</p>
{% comment %} 현재 이 화면을 보는 사람이, 해당 question의 작성자일 경우에만 보여주자{% endcomment %}
{% if request.user == question.user %}
<div>
    <a href="{% url 'polls:update_question' question.pk%}">
        <button>수정</button>
    </a>
</div>

<div>
    <form action="{% url 'polls:delete_question' question.pk%}" method='POST'>
        {% csrf_token %}
        <button>삭제</button>
    </form>
</div>
{% endif %}

<hr>

<form action="{% url 'polls:create_reply' question.pk%}" method='POST'>
    {% csrf_token %}
    {{form}}
    <button>Reply</button>
</form>
<ul>
    {% for reply in question.reply_set.all %}
    <li>
        {{reply.content}} - ({{reply.vote}})
        {% if request.user != reply.user %}
        <form action="{% url 'polls:reply_upvote' question.pk reply.pk %}" method='POST' style = 'display:inline-block'>
            {% csrf_token %}
            <button>+1</button>
        </form>
        {% else %}
        <form action="{% url 'polls:delete_reply' question.pk reply.pk %}" method = 'POST' style = 'display:inline-block'>
            {% csrf_token %}
            <button>삭제</button>
        </form>
        {% endif %}

    </li>
    {% endfor %}
</ul>

{% endblock content %}

03_django/RECAP/polls/templates/polls/question_form.html
{% extends 'base.html' %}

{% block content %}
<form method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <button>go</button>
</form>

{% endblock content %}

03_django/RECAP/polls/templates/polls/question_index.html
{% extends 'base.html' %}

{% block content %}
<h1>Questions</h1>

<ul>
    {% for question in questions  %}
    <li>
        <a href="{% url 'polls:question_detail' question.pk %}">
            {{question.title}}
        </a>
    </li>
    {% endfor %}
</ul>

{% endblock content %}